otel:
  exporter:
    otlp:
      endpoint: http://adot-collector:4317 # Nombre del contenedor Docker del Collector
      protocol: grpc

spring:
  application:
    name: service-b

logging:
  pattern:
    console: '{"timestamp":"%d{yyyy-MM-dd HH:mm:ss}","traceId":"%X{traceId}","spanId":"%X{spanId}","level":"%p","message":"%m"}%n'

management:
  endpoints:
    web:
      exposure:
        include: "*" # Exponer todos los endpoints
  endpoint:
    health:
      enabled: true # Habilitar /actuator/health

